### ISSUE TITLE
How to configure the scene

### ISSUE THREAD

**Issue by maartentromp** [Esri/solutions-widget-utility-network-trace#10]
Thanks a lot for this widget!
Can you explain in more detail how to configure the map/scene and webappbuilder 3D App.
I tried Naperville and my Duch UtilityNetwork in RD_NEW projection, I can't get them to work.
I added the Widget to my 10.6.1 portal, the WAB finds the widget, but the UN is not found.
Should I configure things in config.js like:
"subnetLineLayer": 666,  "UNLayerId": 666,  "FSurl": null"

**Comment by MikeMillerGIS** [comment]
Martin, hopefully this answers your questions, post back if it does not.

https://esri.github.io/solutions-widget-utility-network-trace/

**Comment by maartentromp** [comment]
Hi Michael,
Thank for the quick response! I read the Word document containing the same information. Unfortunatelly the Service, Domains and Tiers are not filled with values, all services and items are owned by the same user. No related errors in the Chrome debugger. Any requirements regarding the published services? Mine are e.g. in ArcGIS Server folders. How does the widget select/find the needed UNM FeatureService from the MapService in the Scene?

**Comment by maartentromp** [comment]
The widget only looks for public-share items. When debugging I see that the reponse of the request "https://<servername>/portal/sharing/rest/search?num=100&start=0&sortField=title&sortOrder=asc&q=owner%3Aunmpoc&f=json" is empty when the items are not shared public. As soon as I share the services (including the UNM-FeatureService) to "public" the combo's Service/Domains/Tiers get filled:-)
Our testserver is connected to the internet so sharing the services public it not possible. Do you see a quick fix?

**Comment by MikeMillerGIS** [comment]
reopening till issue is solved in widget.  Thanks @maartentromp for tracking it down.
