### ISSUE TITLE
Manual barriers parameter to hide in code

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#100]
Manual barriers may be optional and perhaps should have a parameter so developers can hide the block in case they don't want to expose this option in their widget/app.
![image](https://user-images.githubusercontent.com/50338557/131586126-759397c2-e58a-4673-9eb6-5151fd314f8f.png)

**Comment by MikeMillerGIS** [comment]
we could leverage tags in the Trace Config

DISPLAYBARRIERS:True

**Comment by avezina** [comment]
Right now, the trace configuration is not driving the widget UI. You can place as many flags, barriers, and select as many traces you want. 

If we want to do this, we'd have to re-work the wireframe and then only display barriers based on a parameter in the trace config. I believe it would need to come from the trace config somehow. The tag approach is more like a workaround/hack.
Also, since we plan to allow for multiple traces to run concurrently, this adds complications.

What we could do instead is make the barriers option a parameter and we would make it up to the developer to display barriers or not in their own widget and then also leverage the parameter to have an option in ExB to display them for a specific trace config. The presence of manual barriers would not be tied to a specific trace configuration but rather to the widget configurer's decision.

**Comment by MikeMillerGIS** [comment]
ok, lets leave it as is for now
