### ISSUE TITLE
Add option to load flags from selected features?

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#101]
The option could be added to both the starting points and the barriers block where the user can generate flags from a selection of features. Maybe it'll be an option from the dropdown in the 2-part button?
![image](https://user-images.githubusercontent.com/50338557/131586305-1e153744-e183-4d44-88b9-1cdc34048f02.png)

**Comment by MikeMillerGIS** [comment]
For devices and JO, it would have to present the terminals or the user would set them afterwards
for lines and EdgeO, it would place the starting point at start, end or midpoint?  User would need ability to shift the percent along

**Comment by avezina** [comment]
I wonder if we should provide prompt for the terminals, more similar to how it's done in field maps but still allowing for multiple selections when a flag is placed. It forces the user to make a selection. Unless we're happy with it setting a default terminal.
![image](https://user-images.githubusercontent.com/50338557/131701829-773d78f7-ff1b-4dea-a897-f02caf4baac7.png)

**Comment by avezina** [comment]
duplicate of https://github.com/Esri/solutions-widget-utility-network-trace/issues/108
