### ISSUE TITLE
Non-spatial objects as flags and results

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#102]
For flags, we just need a way to bring them in as flags (like via URL parameter)
The lookup (for flag) for actual NSO is outside the scope of UNT.

For result, we need to make sure it can be returned and also to give it some icon to differentiate it.

![image](https://user-images.githubusercontent.com/50338557/146084993-13d64747-b717-4fd9-ab51-ee43ef688f54.png)

**Comment by MikeMillerGIS** [comment]
As long as there is a way to pass them in, there does not need to be a UX to add NSO as flags/barriers
