### ISSUE TITLE
Terminals and filter barrier dropdown needs to be more obvious

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#103]
Open to suggestions here - we need to make terminals dropdown more obvious or use a different approach like suggested here:
https://github.com/Esri/solutions-widget-utility-network-trace/issues/101#issuecomment-910408703

How do I know this is expandable and terminal options are available?
![image](https://user-images.githubusercontent.com/50338557/132419658-bbc0794c-2203-44e2-8674-04e264f6fa7a.png)
![image](https://user-images.githubusercontent.com/50338557/132419676-cfd1c7aa-9e52-4034-81b7-3eb212afc329.png)

**Comment by MikeMillerGIS** [comment]
I terminal is required, i wonder if we should not auto pick one and force the user to select one.  Maybe an icon to inform you.  I think the tag box takes up too much room, but I like that I could set a flag on more than terminal
