### ISSUE TITLE
 Select the results on complete: boolean, default is True

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#104]
![image](https://user-images.githubusercontent.com/50338557/134374364-c8165595-a711-4e75-9c6a-a9ffaae81a41.png)
Right now, select is turned off by default when the results are returned, but someone might want the result to be selected right away. We can then also expose this option in ExB config.

**Comment by avezina** [comment]
Right, doesn't seem like this is working.
![image](https://user-images.githubusercontent.com/50338557/142061344-c4a071e8-f696-4e1d-a41b-c6cbdcd67d09.png)

**Comment by previnWong** [comment]
installed in branch 
https://devtopia.esri.com/WebGIS/arcgis-js-api/tree/prev8048/utilitynetworktrace_111621
