### ISSUE TITLE
UtilityNetwork item must be public to be seen by widget configuration page

### ISSUE THREAD

**Issue by rpplanillo** [Esri/solutions-widget-utility-network-trace#11]
Hello,

I'm Rubén Pérez and I work at Esri Spain. Thank you so much for sharing this fantastic widget!
We detect that the only way to use a UN service with the widget is to make it public. 

We check requests made and we found:

https://[server_name]/portal/sharing/rest/search?num=100&start=0&sortField=title&sortOrder=asc&q=owner%3Asiteadmin&f=json

It only responses with public items belonging to user (siteadmin).

thanks!

**Comment by rpplanillo** [comment]
thanks!

**Comment by MikeMillerGIS** [comment]
@maartentromp want to submit a PR with the changes?

**Comment by MikeMillerGIS** [comment]
@maartentromp submitted a PR with this fix, please test again and reopen if still an issue.
