### ISSUE TITLE
Dismissing Clear all window needs to act like cancel

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#127]
Right now if I dismiss (X) the clear all window, I am not able to open it again

https://user-images.githubusercontent.com/50338557/136291847-d95376b9-1951-4f2e-8db3-8d714ff814d6.mp4

.

**Comment by previnWong** [comment]
installed in
https://devtopia.esri.com/WebGIS/arcgis-js-api/tree/prev8048/utilitynetworktrace_111621
