### ISSUE TITLE
Cannot add a flag on top of the Highlighted features

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#131]
Cannot add a flag on top of the Highlighted features

http://dev0016770.esri.com/arcgis-js-api/test-apps/traceTest.html?webmap=9b4bc7229adc4e529b46bbbb126fa2a0&portal=https://avezina2.esri.com/portal

![image](https://user-images.githubusercontent.com/50338557/137404553-fa9ddde2-e5a0-485a-9dff-299e3a3b73a8.png)

https://user-images.githubusercontent.com/50338557/137404990-4b39ec6b-291f-4cfa-85e2-0166dd0d15e4.mp4

**Comment by previnWong** [comment]
installed in
https://devtopia.esri.com/WebGIS/arcgis-js-api/tree/prev8048/utilitynetworktrace_111621
