### ISSUE TITLE
The list options popper is cut out because panel height is dependent on items in list

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#136]
The list options popper is cut out when a small number of features is listed.
Perhaps we should have a minimum panel heigh despite the number of features listed. A more consistent height would also be better when switching between panes.
![image](https://user-images.githubusercontent.com/50338557/139124988-394e28d2-4acd-4fb8-a263-6cadabc4285e.png)

**Comment by avezina** [comment]
@asangma Do you know if there's something we can do about this? Could the popper display "on top" of the widget?

**Comment by asangma** [comment]
@avezina I think I min-height would be a good idea. I know I had added one in my styling PR. Not sure if it got included or overwritten in a merge.

That being said, the min-height will help, but it will still be somewhat brittle.

As a note, we might be able to get away with not adding a heading to the Panel. That should help reduce the height of the popover.

**Comment by asangma** [comment]
As far as the Popper rendering on top of the widget, I believe that would require the popover manager to be wrapped around the node which contains the widget...which seems not doable.

**Comment by avezina** [comment]
@asangma I think min-height and removing the header should do the work! 
@previnWong
