### ISSUE TITLE
Improve experience for adding flags

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#143]
Open to suggestions but here's an idea:

1. Move the ( Add ) button at the top of the list of flags, so for example in the screenshot below, adding a Barrier is still possible without having to scroll at the bottom of the list. If the ( Add ) button is moved to the top, do we then need to reverse the list with the most recent listed on top?
![image](https://user-images.githubusercontent.com/50338557/139757373-62ea89ee-e2b1-4bd9-a0f4-d022113a39ef.png)
![image](https://user-images.githubusercontent.com/50338557/139757411-e10b68cc-6435-4767-a1ef-aa5e2dc01c1f.png)

2. Remove the icons and center the text
![image](https://user-images.githubusercontent.com/50338557/139757520-ea9f6eaf-8099-47fa-924a-5995bc73273e.png)

3. Add the checkbox as described here https://github.com/Esri/solutions-widget-utility-network-trace/issues/142

4. SHould we allow for only 1 expanded at the time?
![image](https://user-images.githubusercontent.com/50338557/139757647-4b4fc2bc-a150-46fd-89ae-9efc8f655c06.png)

5. Add option to "remove all" at the bottom of each list of flags (if 2+)

**Comment by asangma** [comment]
1. We had similar discussions in various other cases, and have consistently landed on putting the `+` button at the bottom. As you suggested, it would require flipping the order of the things being added. We haven't see that pattern really anywhere else on the interwebs. :)
2. I think the icon here helps. It's not accurate, but it's helpful. You could also use [pin-tear](https://esri.github.io/calcite-ui-icons/#pin-tear) or [pin-plus](https://esri.github.io/calcite-ui-icons/#pin-plus). But I'd actually suggest using the larger icon (32)
3. I'm totes confused on this one.
4. That might be nice. You'd have to manage that manually.
5. This seems like a nice convenience. I'd suggest adding that above the list as a text only button (`<calcite-button appearance="transparent" />`). It's probably better to keep away from the add button.

**Comment by avezina** [comment]
1. Alright then! 😄 @previnWong we may be able to play around with the scroll and have the pane re-load to the add button for that block (a bit like the template picker nightmare we had to deal with in SE? but hopefully easier)
2. Agreed for a bigger icon, and I like pin-plus.
3. It would look like this, when adding a Barrier - you can opt into making this a filter barrier before you even add the point
![image](https://user-images.githubusercontent.com/50338557/139950012-de3eac1c-d5ad-4060-8c4f-e668e36b3c71.png)
4. Cool, we'll see if we have the time.
5. Good idea.

**Comment by asangma** [comment]
1. Wait...did you mean you're planning to put the `+` on top?
2. Cool
3. I think this is a good impulse. I'm not sure if the user will see that there. Might be worth it to consider two add buttons in the Barriers block. One for "add barrier" and one for "add filter barrier"...?

**Comment by avezina** [comment]
1 Nope. Sorry for the confusion. I meant that it would be better if the pane scrolled down enough to show the `+`
![2021-11-02_14-22-26](https://user-images.githubusercontent.com/50338557/139953838-1e8c8865-312f-4443-a8e0-e6ced52a28ad.gif)

3. That's a good idea, although depends how often people user filter barriers... @previnWong thoughts?

**Comment by MikeMillerGIS** [comment]
i like the two buttons for add barriers, add barriers, add filter barriers

**Comment by avezina** [comment]
@asangma somewhat like this?.. perhaps with a smaller font.

![image](https://user-images.githubusercontent.com/50338557/139961907-58d0a857-d152-420d-ba82-0fcd80db4e11.png)

@MikeMillerGIS do you think these come up often enough for them to deserve their own button?

**Comment by asangma** [comment]
@avezina Yes! Nice. And yeah, I agree that they would look a bit less beefy if we use `scale="s"`.

**Comment by avezina** [comment]
Pushing the buttons change to the next release.

**Comment by avezina** [comment]
Let's push this change to 4.23
