### ISSUE TITLE
Export trace results

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#159]
When we look at how we will export the trace results (selection, aggregated geometry, outage area etc), let's review how the Export was implemented in the Suitability Modeler widget.
Right now, they a creating a new imagery item in the org.
![image](https://user-images.githubusercontent.com/50338557/143961055-f5eca11e-225d-41f5-b3d2-956cc22aa6fe.png)

Perhaps we just do something similar with the option to export as different outputs (feature collection, feature layer, csv, gdb, etc)

**Comment by MikeMillerGIS** [comment]
this would be a good start, but we need to see the requirements from Howard to know if they need to append to a known service

**Comment by avezina** [comment]
closing this, have a requirements issue in devtopia
