### ISSUE TITLE
List of selected features is not returned

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#168]
> The Utility Trace works fine, but I have some issues with the results. 
> 
> When I click on the Features in the results, I see the different layers, but when I click on an individual feature, the widget is broken! I can’t select anything else, no trace, no Clear All. Only a refesh works now.
> See attached mp4 for clarification.

https://user-images.githubusercontent.com/50338557/145867323-cbd82153-2e17-410d-a937-c38f2ed9b315.mp4

**Comment by MikeMillerGIS** [comment]
would like to see what is going on in the dev console.  looks like a error is causing the first to break.  Can we get app link?

**Comment by MikeMillerGIS** [comment]
just need creds - http://unm.esri.nl/unm/un_js_trace422.html
