### ISSUE TITLE
Handle a trace failure, such as No valid subnetwork controllers found

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-widget-utility-network-trace#41]
When a trace cannot complete, an error is returned, this needs to be handled and displayed to the users.

REPO:
- Add barriers to isolate the flag
- Run an isolated trace

Error:
traceTest.html:1 Uncaught (in promise) Error {name: "request:server", details: {…}, message: "No valid subnetwork controllers found."}

**Comment by previnWong** [comment]
addressed in latest commit, please pull and verify.

**Comment by avezina** [comment]
An error is returned 
![image](https://user-images.githubusercontent.com/50338557/126721807-b8f76b0d-4918-4bc2-a7ff-3bb39544ee13.png)

**Comment by previnWong** [comment]
yes, that's what is suppose to do.

**Comment by MikeMillerGIS** [comment]
verified
