### ISSUE TITLE
Disable run button when no trace is selected

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-widget-utility-network-trace#42]
Currently, it still runs and ran one of the traces
![image](https://user-images.githubusercontent.com/2707285/126545661-f58fda62-0c52-4a00-9fcd-a683946b098f.png)

**Comment by avezina** [comment]
The button itself won't be disabled, but it should display a warning that a trace needs to be selected prior to running, and trace should not run.
![image](https://user-images.githubusercontent.com/50338557/126545998-79bb3ac8-968f-45c5-ab96-778e836e63c4.png)

**Comment by avezina** [comment]
Warning message has been implemented
