### ISSUE TITLE
Keep focus on Add buttons after adding barrier/location

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-widget-utility-network-trace#44]
Should we keep focus on the Add button?  Currently, after you add a location, the button is deselected.

**Comment by avezina** [comment]
What's the most common workflow, one or many flags? I think the user should purposefully click add if they want to add a flag, other they need to click add to deactivate the button or they may add a flag by accident.

**Comment by avezina** [comment]
A pane is shown to guide the action with this action, add button should not remain active. 
![image](https://user-images.githubusercontent.com/50338557/129985909-82752455-4bc2-4da7-99d5-b1d5039c6ae5.png)
