### ISSUE TITLE
Fix the size of the widget or fix widget panel css

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-widget-utility-network-trace#45]
The transition from the main screen to the All Starting points screen is odd.  The form changes size:
![image](https://user-images.githubusercontent.com/2707285/126546321-0008e102-dff0-461a-8bb7-0754c4e40231.png)

to
![image](https://user-images.githubusercontent.com/2707285/126546350-03a912be-c490-4f37-9f23-0aed8bbbfc0c.png)

Also, why the horizontal scrol

**Comment by avezina** [comment]
Fix form resize:
![image](https://user-images.githubusercontent.com/50338557/137520920-3f1031b7-5ef8-4ca8-8470-83aa1e086ac1.png)
![image](https://user-images.githubusercontent.com/50338557/137520938-18ea0a68-d612-444a-8c5f-d3b4c2bc26e7.png)

**Comment by asangma** [comment]
I the horizontal scroll bar is being caused by a style in CalciteTabNav.
Issue here: https://github.com/Esri/calcite-components/issues/3279

**Comment by asangma** [comment]
I think the weird heading bottom-border thing is being caused by the widget changing widths while the tab component is trying to calculate stuff. Addressing the widget width troubles should remedy that.
