### ISSUE TITLE
All Starting Points - Pop up does not work on the first two entries

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-widget-utility-network-trace#46]
Could only get the ... pop up to work on the 3rd
![image](https://user-images.githubusercontent.com/2707285/126546515-0a68f503-885b-4142-bbcc-44cd20398e0c.png)

**Comment by MikeMillerGIS** [comment]
These two were previous used in a trace, I had results.  Odd that one a trace is run with a location, I could not remove it

**Comment by avezina** [comment]
I can't repro this anymore, @MikeMillerGIS can you?
Latest build: http://dev0016770.esri.com/arcgis-js-api/test-apps/traceTest.html

**Comment by MikeMillerGIS** [comment]
same here
