### ISSUE TITLE
Feature added as start twice

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-widget-utility-network-trace#51]
- Start with a clean app
- Click to activate the Add Button
- Click Run, get the error message
- Click to active the Add Button again
- click on a water main, it will be added twice
![image](https://user-images.githubusercontent.com/2707285/126822636-4df5c04c-7bf8-459e-b969-4f6e454ac87d.png)

**Comment by previnWong** [comment]
ugh, probably initiated 2 instances of clickHandler.

**Comment by avezina** [comment]
I can't repro this anymore, @MikeMillerGIS can you?

**Comment by MikeMillerGIS** [comment]
let me pull again and do two hops, an install, an build and pray I got the new version :)

**Comment by MikeMillerGIS** [comment]
same here, no longer repo
