### ISSUE TITLE
Increase intersection tolerance for adding flags - may need to request additional parameter for hitTest

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#60]
I'm not able to add a flag (error is shown) even if I click close to a line.
Is this using pixels?

![2021-07-27_10-06-27](https://user-images.githubusercontent.com/50338557/127197556-764f1e9a-8b2e-435d-89ae-e222b7f02e43.gif)

**Comment by previnWong** [comment]
I do not have control of this.  I'm using JS API map view hit test and it doesn't have options to pass in tolerance.
https://developers.arcgis.com/javascript/latest/api-reference/esri-views-MapView.html#hitTest
