### ISSUE TITLE
Provide a progress indicator for each trace

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#63]
![image](https://user-images.githubusercontent.com/50338557/127237635-d1e963c2-9e39-43e9-ad2f-202928ecbc8a.png)

![2021-07-27_15-53-18](https://user-images.githubusercontent.com/50338557/127237762-1f2e75c5-b95e-4324-8332-b56ce35bc64d.gif)

**Comment by avezina** [comment]
Ah looks like it did not really fail, it look a long time to show up and then could not be expanded... connected trace issues

**Comment by previnWong** [comment]
we might need progress indicator for each trace, cuz I make the progress go away after the first trace comes back

**Comment by avezina** [comment]
And we may ned to limit the number of traces that can be run at once?

**Comment by MikeMillerGIS** [comment]
![image](https://user-images.githubusercontent.com/2707285/127381857-9041d525-f240-448b-bd26-933195a568d7.png)
