### ISSUE TITLE
What should be the default palette for the highlight colors?

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#64]
![image](https://user-images.githubusercontent.com/50338557/127366500-3d9632a7-ef8c-4364-bd6f-abb7117357f3.png)

**Comment by previnWong** [comment]
Here's the current colors, please update what you think they should be

  { color: [255, 0, 0, 1], haloOpacity: 0.9, fillOpacity: 0.2 },
  { color: [0, 255, 0, 1], haloOpacity: 0.9, fillOpacity: 0.2 },
  { color: [0, 0, 255, 1], haloOpacity: 0.9, fillOpacity: 0.2 },
  { color: [255, 255, 0, 1], haloOpacity: 0.9, fillOpacity: 0.2 },
  { color: [255, 0, 255, 1], haloOpacity: 0.9, fillOpacity: 0.2 }

I only did 5 levels, then it repeats itself.  maybe go to 10 if you want.

**Comment by avezina** [comment]
Max colors would be based on the max number of traces we allow? https://github.com/Esri/solutions-widget-utility-network-trace/issues/63

I think we should look at these and discuss with Alan, but probably chose something colorblind-friendly:

- cyan: rgb(0,255,255) - existing ArcGIS selection color
- yellow: rgb(255,255,0) - existing ArcGIS selection color
- pink: rgb(255,0,255)

After that, if we want to allow for more than 3, we could have dark blue and red (although I have doubts about pink and red not being in conflict...)
![image](https://user-images.githubusercontent.com/50338557/127370607-6dbf1c06-3b4d-4c8f-b69c-bf3533eec55d.png)

**Comment by avezina** [comment]
Not applicable anymore given one selection is displayed at the time.

**Comment by avezina** [comment]
Reopening this, may still need it for aggregate geometry

**Comment by avezina** [comment]
Closing this, we have defined one and can modify it again later if needed.
