### ISSUE TITLE
Remove h4 element from Run and Start Over blocks

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#73]
Remove h4 element from Run and Start Over blocks, and increase text size for button? Default seems small
![image](https://user-images.githubusercontent.com/50338557/127402702-e549ebc2-c4c6-48fd-bae8-86d9cf6e666b.png)

**Comment by previnWong** [comment]
no control of this, it's calcite

**Comment by avezina** [comment]
It was removed
