### ISSUE TITLE
Expand option to select terminals on load when flag added on feature with terminals?

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#75]
We may need to rethink this whole dropdown for terminals idea.

Should we expand the option to select terminals on load when a flag is added on a feature with terminals?
Or maybe we just need a way to indicate that there are terminals set?
![image](https://user-images.githubusercontent.com/50338557/127404075-aa2f8939-5c2e-4f4d-84b7-c2f55cb06c9b.png)

@MikeMillerGIS thoughts?

I don't know if we should add an icon to indicate terminals, and or a dropdown arrow. Also have to see what's possible.
![image](https://user-images.githubusercontent.com/50338557/127404208-13c4cd75-4af0-4124-998b-a84a9e01287e.png)

**Comment by previnWong** [comment]
terminals will be added to the ellispses options, haven't done it yet.  have to click to expand for now.
