### ISSUE TITLE
Displaying aggregated geometry and selection for traces

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#80]
### Cases

**Selection only:** 

- Return selected features results list
- Highlight selection on the map (cyan) : Default = enabled on load results
- Provide option to export selected results and stats/functions summary (enhancement)

**Aggregate only:** 

- Selected features results list is not provided
- Graphics are displayed on the map (color 1): Default = enabled on load results
- Cannot export features other than stats/functions summary

**Both Selection & Aggregate:** 

- Return selected features results list
- Highlight selection on the map (cyan): Default = disabled on load results
- Graphics are displayed on the map (color 2): Default = enabled on load results
- Provide option to export selected results and stats/functions summary (enhancement)

**Notes:**
- Both the selection and the graphics can be shown for a given trace (not mutually exclusive).
- Multiple selections can be shown at once. Selections on the map will behave as "one selection set" for other widgets/actions.
- Multiple graphics can be shown at once. Graphics are for display purposes only.
- When multiple traces are run, the first trace rendered is displayed on the map (selection or graphics), the other ones off.
___

### UI changes

![image](https://user-images.githubusercontent.com/50338557/128777742-01ed9668-ee2c-48e3-b523-c6f48b43f958.png)

**Comment by MikeMillerGIS** [comment]
I like it!

**Comment by avezina** [comment]
Here's Alan's new suggestion:
![image](https://user-images.githubusercontent.com/50338557/128785694-b54d00b8-c9e4-4bd6-ac71-7ba4884f2694.png)

Some of the stuff will need some custom styling like the "trace completed" with the border on top.

**Comment by MikeMillerGIS** [comment]
This looks very clean, I like the view features and leverage the old arrow button area for the ...
