### ISSUE TITLE
Cancel flag still creates flag

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#93]
![2021-08-30_14-34-59](https://user-images.githubusercontent.com/50338557/131408909-abdb5ff9-9ba2-4e7b-9843-e24253a0eec7.gif)

**Comment by previnWong** [comment]
installed here
https://devtopia.esri.com/WebGIS/arcgis-js-api/tree/prev8048/utilitynetworktrace_111621

**Comment by avezina** [comment]
Looks good now
